application: fisatbtechapplication
version: 3
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: jscript
- url: /images
  static_dir: images
- url: /status
  script: appstatus.py
- url: /filldb
  script: appstatus.py
- url: /offline
  script: offlinemain.py
- url: /offsubmit
  script: offlinemain.py
- url: /download
  script: download.py
- url: /vdownload
  script: download.py
- url: /fbmdownload
  script: download.py
- url: /fbpdownload
  script: download.py
- url: /mkdownload
  script: download.py
- url: /rldownload
  script: download.py
- url: /search
  script: search.py
- url: /editstatus
  script: edit.py
- url: /editmarks
  script: edit.py
- url: /map
  script: edit.py
- url: /rank
  script: rank.py
- url: /rankcmd
  script: rank.py
- url: /.*
  script: main.py

